import { Metadata } from "next";
import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "prducts 페이지",
  description: "prducts 페이지입니다.",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav className={styles.nav}>
        <span className={styles.tab}>남성옷</span>
        <span className={styles.tab}>여성옷</span>
        <section>{children}</section>
      </nav>
    </>
  );
}
